export const plans={
  3:{label:'3-acre compact homestead',thesis:'Enough for a comfortable home, serious garden, small orchard, chickens, workshop and meaningful privacy when parcel shape, sun and infrastructure cooperate.',reality:'Three acres punishes poor layout. House siting, septic reserve and shade can consume the useful core quickly—buy shape and sun, not headline acreage.',budget:[['~1.0 ac','house · drive · well · septic · shop'],['~0.5 ac','garden · greenhouse · compost'],['~0.5 ac','orchard · chickens · flexible yard'],['~1.0 ac','privacy buffer · paths · future use']],well:[205,475],zones:[[245,340,185,105,'home','infrastructure','HOUSE','comfortable core'],[455,330,180,145,'food','food','KITCHEN GARDEN','beds · compost'],[650,355,110,88,'food','food','GREENHOUSE','season extension'],[150,280,125,100,'infra','infrastructure','SHOP','tools · storage'],[420,180,235,105,'food','food','ORCHARD','fruit · berries'],[680,185,170,130,'livestock','livestock','CHICKENS','coop · run'],[75,70,800,85,'privacy','privacy','TREE BUFFER','privacy · habitat'],[620,480,205,70,'infra','infrastructure','SEPTIC RESERVE','concept only']]},
  10:{label:'10-acre working homestead',thesis:'Room for a serious household food system, workshop, chickens or modest grazing, and a meaningful woodlot without requiring a full farm operation.',reality:'Ten acres creates options without automatically creating a farm. Keep high-frequency chores close to the house; let lower-frequency uses absorb distance.',budget:[['1–2 ac','serviced core · shop · daily yard'],['2–3 ac','garden · greenhouse · orchard'],['2–3 ac','flex field · poultry · grazing'],['3+ ac','woodlot · trails · habitat']],well:[190,475],zones:[[235,350,175,100,'home','infrastructure','HOUSE','mudroom · kitchen axis'],[430,325,185,145,'food','food','KITCHEN GARDEN','intensive beds'],[635,345,105,92,'food','food','GREENHOUSE','propagation'],[110,275,130,110,'infra','infrastructure','SHOP / BARN','tools · storage'],[380,170,310,115,'food','food','ORCHARD + BERRIES','perennial food'],[715,175,230,285,'livestock','livestock','FLEX FIELD','poultry · grazing'],[55,55,875,88,'privacy','privacy','WOODLOT + TRAILS','privacy · fuel · habitat'],[565,485,215,72,'infra','infrastructure','SEPTIC / RESERVE','conceptual siting']]},
  20:{label:'20-acre smallholding',thesis:'A real smallholding scale: room for livestock, meaningful woodlot, habitat and larger fields—with a matching increase in fencing, mowing, equipment and daily responsibility.',reality:'Twenty acres helps only when the extra land has a job. Maintenance, fencing, invasive plants and drainage scale with managed area even when food production does not.',budget:[['~2 ac','household core · barn · services'],['3–4 ac','garden · greenhouse · orchard'],['5–7 ac','rotational pasture · flexible field'],['7+ ac','woodlot · habitat · expansion']],well:[120,510],zones:[[150,390,165,95,'home','infrastructure','HOUSE','compact service core'],[335,370,165,130,'food','food','GARDEN','household + surplus'],[515,390,95,86,'food','food','GLASSHOUSE','season extension'],[70,285,170,105,'infra','infrastructure','BARN / SHOP','feed · equipment'],[270,225,280,115,'food','food','ORCHARD','fruit · berries'],[575,195,170,170,'livestock','livestock','PADDOCK A','rotation'],[760,195,170,170,'livestock','livestock','PADDOCK B','rotation'],[650,385,280,115,'livestock','livestock','FLEX FIELD','hay · rest'],[60,55,870,115,'privacy','privacy','WOODLOT / HABITAT','trails · fuel · buffer'],[360,520,195,58,'infra','infrastructure','SEPTIC RESERVE','concept only']]}
};
export const production={
  garden:{code:'FOOD / 01',name:'Kitchen-scale abundance',load:'3/10',copy:'Intensive beds, herbs, berries and a few perennial crops materially improve food quality without making the property operate like a farm.',ribbon:[['beds',34],['berries',22],['compost',16],['flex',28]],build:['Water close to the garden','Good sun + paths before more beds','Compost + simple protected growing'],animals:[['Chickens','optional'],['Bees','optional'],['Larger stock','no need']],friction:['Peak-season watering','Preservation if surplus grows','Vacation coverage for animals']},
  household:{code:'FOOD / 02',name:'Household food system',load:'6/10',copy:'A larger garden, greenhouse, orchard, storage and chickens can make a meaningful share of household food visible and seasonal without requiring farm-scale acreage.',ribbon:[['annuals',28],['orchard',24],['glass',12],['animals',14],['flex',22]],build:['Wash/store workflow','Irrigation + season extension','Freezer/cold-storage capacity'],animals:[['Chickens','strong fit'],['Bees','good fit'],['Sheep/goats','possible later']],friction:['Daily animal routine','Harvest + preservation peaks','Feed/storage logistics']},
  smallholding:{code:'FOOD / 03',name:'Smallholding operation',load:'9/10',copy:'Pasture rotation, larger poultry numbers or small ruminants move the property from a garden with animals toward an operation that needs real infrastructure and daily coverage.',ribbon:[['crops',18],['orchard',14],['service',14],['pasture',38],['woodlot',16]],build:['Fencing + gates + water','Barn/feed/equipment storage','Manure + winter-feed plan'],animals:[['Chickens','core'],['Bees','easy add'],['Sheep/goats','real commitment']],friction:['365-day care','Fencing + vet + winter feed','Equipment and replacement costs']}
};
export const archetypes={
  fixer:{label:'Current leading strategy',name:'Older house on excellent land',copy:'Look for structurally sound but cosmetically tired acreage with functioning access, well, septic and useful outbuildings. Renovate what is visible; avoid paying twice for infrastructure.',capital:'Medium–high',risk:'Medium',diy:'High',time:'Short',inspect:'Structure · roof · drainage · well record/yield · water quality · septic inspection · legal access · zoning · outbuildings · internet'},
  turnkey:{label:'Low-friction alternative',name:'Ready rural homestead',copy:'Pay more for a house and infrastructure that already meet your comfort target. This makes sense when time, certainty and remote-work continuity are worth more than sweat-equity upside.',capital:'High',risk:'Lower',diy:'Low–medium',time:'Immediate',inspect:'Infrastructure records · water/septic condition · energy performance · zoning · land usability · outbuilding condition'},
  raw:{label:'Control-heavy route',name:'Raw land + designed build',copy:'Maximum design control comes with the greatest site-risk exposure: approvals, access, clearing, drainage, well, wastewater, power, construction sequencing and carrying costs all arrive before the lifestyle does.',capital:'High / uncertain',risk:'Highest',diy:'Selective',time:'Long',inspect:'Buildability · access · survey · zoning · conservation/flood constraints · water · septic feasibility · power/solar · financing'}
};
