export const sources = {
  london:{label:'ECCC · London normals',url:'https://climate.weather.gc.ca/climate_normals/results_1991_2020_e.html?climate_id=6144473'},
  abbotsford:{label:'ECCC · Abbotsford normals',url:'https://climate.weather.gc.ca/climate_normals/results_1991_2020_e.html?climate_id=1100030'},
  victoria:{label:'ECCC · Victoria Airport normals',url:'https://climate.weather.gc.ca/climate_normals/results_1991_2020_e.html?climate_id=1018620'},
  via:{label:'VIA · London → Toronto',url:'https://www.viarail.ca/en/explore-our-destinations/trains/ontario-and-quebec/london-to-toronto'},
  wce:{label:'TransLink · West Coast Express',url:'https://www.translink.ca/schedules-and-maps/west-coast-express'},
  alr:{label:'BC ALC · ALR ownership',url:'https://www.alc.gov.bc.ca/use-of-alr-land/buying-and-owning-land-in-the-alr/'},
  wells:{label:'Ontario · private wells',url:'https://www.ontario.ca/page/wells-your-property'},
  septic:{label:'Ontario · septic systems',url:'https://www.ontario.ca/page/septic-systems'},
  solar:{label:'NRCan · solar PV',url:'https://natural-resources.canada.ca/energy-efficiency/solar-photovoltaic-energy-buildings'},
  fcc:{label:'FCC · 2025 farmland values',url:'https://www.fcc-fac.ca/en/about-fcc/media-centre/news-releases/2026/canadas-2025-farmland-values-climbed'},
  mission:{label:'REW · 10-acre Mission example',url:'https://www.rew.ca/properties/8573-s-river-road-mission-bc'}
};
export const regions = {
  ontario:{name:'Southwest Ontario',route:'Norfolk → Elgin → Middlesex',thesis:'The practical baseline: productive rural land, real towns nearby, and the cleanest route back to Toronto when work still occasionally pulls you in.',winter:'−5.4°C',winterNote:'London · January daily mean, 1991–2020',access:'2h33',accessNote:'London → Toronto average · 41 weekly VIA departures shown',market:'Lower of 3',marketNote:'Planning judgment · FCC says Ontario farmland +2.2% in 2025',watch:'Winter heating, snow operations, parcel zoning, well yield, septic condition and drainage.',why:'Existing rural houses can bundle the expensive invisible infrastructure—access, well, septic and outbuildings—then let you improve the visible parts gradually.',cap:{mildness:4.5,value:8,privacy:8,self:8.5},anchor:{toronto:9.2,vancouver:1,remote:7.4},src:[sources.london,sources.via,sources.fcc]},
  fraser:{name:'Fraser Valley',route:'Mission → Chilliwack → Agassiz',thesis:'The climate-and-access contender: much milder winters and a real Vancouver commuter-rail option, with more pressure on land price and use.',winter:'3.7°C',winterNote:'Abbotsford · January daily mean, 1991–2020',access:'≈75m',accessNote:'Mission City → Waterfront on published weekday WCE runs',market:'Highest pressure',marketNote:'10-acre Mission listing example · $1.5488M · Aug 2026',watch:'ALR status, local zoning, fill rules, flood/riparian constraints, parcel price and whether Vancouver access actually serves your job.',why:'The winter and growing-season experience is gentler. Mission gives the shortlist a direct weekday rail connection to downtown Vancouver.',cap:{mildness:9,value:4,privacy:6.5,self:7.2},anchor:{toronto:2,vancouver:9.2,remote:8},src:[sources.abbotsford,sources.wce,sources.alr,sources.mission]},
  island:{name:'Vancouver Island',route:'Cowichan → Nanaimo hinterland',thesis:'The lifestyle wildcard: maritime climate, strong homestead character and more separation from big-city life—best when work becomes genuinely location-independent.',winter:'4.6°C',winterNote:'Victoria Airport climate proxy · January daily mean, 1991–2020',access:'Remote-led',accessNote:'Major-city access depends on ferry/air and exact parcel',market:'Premium',marketNote:'Qualitative signal · parcel research required',watch:'Ferry/air dependence, hospital distance, wildfire/water constraints by micro-region and whether island separation stays attractive over time.',why:'For a fully remote career, the island can exchange metropolitan convenience for mildness, privacy and a strong rural-lifestyle fit.',cap:{mildness:9.4,value:5.2,privacy:8.5,self:8},anchor:{toronto:1,vancouver:5.8,remote:8.4},src:[sources.victoria]}
};
export const systems = {
  water:{code:'SYS / WATER',principle:'Own the source. Back up the pump.',flow:['Aquifer','Well','Pump','Pressure','Treatment','House'],title:'A private well is simple until the pump stops.',copy:'Learn water testing, filters, the pressure system and wellhead protection. Keep enough stored water or backup power to bridge an outage.',effort:'Low–moderate',risk:'High',pro:'Licensed well work',resilience:'Storage + backup power'},
  waste:{code:'SYS / WASTE',principle:'Protect the soil system you already paid for.',flow:['House','Tank','Treatment','Distribution','Leaching bed'],title:'Septic is quiet infrastructure with expensive failure modes.',copy:'Know the system, avoid hydraulic and chemical abuse, inspect/pump appropriately, protect the field from traffic and preserve room for a replacement area.',effort:'Low',risk:'High',pro:'Design + regulated service',resilience:'Inspection + reserve area'},
  power:{code:'SYS / POWER',principle:'Resilience beats ideological disconnection.',flow:['Grid','Solar','Inverter','Battery','Critical loads','Generator'],title:'Keep a useful grid connection if the property already has one.',copy:'Treat solar and storage as resilience infrastructure. True off-grid PV normally needs storage; grid-optional design can fail gracefully without recreating a utility connection you already own.',effort:'Low after install',risk:'High in outages',pro:'Electrical / interconnection',resilience:'Battery + generator'},
  heat:{code:'SYS / HEAT',principle:'Envelope first. Then two ways to stay warm.',flow:['Envelope','Heat pump','Distribution','House','Wood / fuel backup'],title:'Canadian comfort is a redundancy problem.',copy:'Reduce the heat load before adding equipment. Use an efficient primary system and keep a second heat source for outages and extreme cold.',effort:'Moderate',risk:'Critical in winter',pro:'HVAC + chimney/fuel safety',resilience:'Second heat source'}
};
